# fly.toml file generated for throbbing-haze-3823 on 2023-04-05T11:33:59-07:00

app = "throbbing-haze-3823"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "sea"
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
