# fly.toml file generated for throbbing-haze-3823 on 2023-04-05T11:33:59-07:00

app = "kaz-test"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ams"
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[mounts]
source = "kaz_test_data"
destination = "/data"
initial_size = "1gb"
